In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sqlalchemy import create_engine

engine = create_engine('postgresql://postgres:Postg_anderzon@localhost:5432/mi_primera_bd')

In [3]:
df_cargo = pd.read_csv('../data_lake/cargo.csv')
df_cargo.to_parquet(
    '../data_sets/cargo.parquet',
    engine='pyarrow',
    index=False,
    compression='snappy' )
df_cargo.isna().sum()

id_cargo           0
nombre_cargo       0
salario_mensual    0
dtype: int64

In [3]:
du = df_cargo[df_cargo.duplicated()]

In [4]:
#duplicados = df_cargo.duplicated(subset=['id_cargo']).sum()
#duplicados_por_email = df_cargo[df_cargo.duplicated(subset=['id_Cargo'], keep=False)]
df_ventas = df_cargo.drop_duplicates(subset=['id_cargo'], keep='first')

In [5]:
print(df_cargo.head(3),'\n')
df_cargo['salario_mensual'] = df_cargo['salario_mensual'].astype(float)
print(df_cargo.dtypes)

   id_cargo             nombre_cargo  salario_mensual
0         1        Gerente de tienda            45000
1         2               Subgerente            32000
2         3  Encargado de inventario            24000

id_cargo             int64
nombre_cargo           str
salario_mensual    float64
dtype: object

In [46]:
df_tienda = pd.read_csv('../data_lake/tienda.csv')
df_tienda.isna().sum()
df_tienda.to_parquet(
    '../data_sets/tienda.parquet',
    engine='pyarrow',
    index=False,
    compression='snappy' 
    )

In [45]:
df_empleado= pd.read_csv('../data_lake/empleado.csv')
df_empleado.isna().sum()
df_empleado.to_parquet(
    '../data_sets/empleado.parquet',
    engine='pyarrow',
    index=False,
    compression='snappy' )
# limpio

In [8]:
df_empleado.head(3)

,id_empleado,codigo_empleado,nombre,edad,fecha_contratacion,id_tienda,id_cargo,salario
0,1,EMP001,Alejandro Mateo,42,15/03/2025,1,1,45000
1,2,EMP002,Santiago Sebastián,38,20/05/2025,2,1,45000
2,3,EMP003,Leonardo Diego,45,10/02/2025,3,1,45000

In [9]:
df_region =pd.read_csv('../data_lake/region.csv')
df_region.isna().sum()

id_region        0
nombre_region    0
codigo_iso       0
dtype: int64

In [44]:
df_region.head(3)
df_region.to_parquet(
    '../data_sets/region.parquet',
    engine='pyarrow',
    index=False,
    compression='snappy' )

In [14]:
df_categoria = pd.read_csv('../data_lake/categoria.csv')

In [15]:
df_categoria.head()

   id_categoria  nombre_categoria                           descripcion
0             1       Electrónica   Dispositivos tecnológicos y gadgets
1             2             Hogar  Artículos para el hogar y decoración
2             3         Alimentos               Consumibles y abarrotes
3             4              Ropa                 Vestimenta y textiles
4             5  Cuidado Personal                     Higiene y belleza

In [16]:
df_categoria.to_parquet(
    '../data_sets/categoria.parquet',
    engine='pyarrow',
    index=False,
    compression='snappy' )

In [17]:
df_categoria.head(3)

   id_categoria nombre_categoria                           descripcion
0             1      Electrónica   Dispositivos tecnológicos y gadgets
1             2            Hogar  Artículos para el hogar y decoración
2             3        Alimentos               Consumibles y abarrotes

In [13]:
df_productos =pd.read_csv('../data_lake/productos.csv')
df_productos.isna().sum()

id_p               0
id_cat             0
nombre_producto    0
stock              1
dtype: int64

In [ ]:
# rellenar nulo con la media y renombrar columnas
df_productos = df_productos.rename(columns={'id_p':'id_producto', 'id_cat':'id_categoria'})
df_productos.stock = df_productos.stock.fillna(df_productos.stock.mean())
df_productos.isna().sum()

id_producto        0
id_categoria       0
nombre_producto    0
stock              0
dtype: int64

In [42]:
df_productos.to_parquet(
    '../data_sets/productos.parquet',
    engine='pyarrow',
    index=False,
    compression='snappy' )
df_productos.head(3)

   id_producto  id_categoria      nombre_producto  stock
0            1             1     Smartphone Alpha    9.0
1            2             1  Audífonos Bluetooth   12.0
2            3             1      Cargador Rápido   13.0

In [45]:
df_compras = pd.read_csv('../data_lake/compras.csv')
df_compras = df_compras.rename(columns={'id_productos': 'id_producto'})
df_compras.insert(1, "id_compra", range(1, len(df_compras) + 1))

In [46]:
df_compras

,id_producto,id_compra,fecha_adq,cant_unidad,costo_u,costo_may_x3,precio_u,precio_may_x3
0,1,1,15/01/2025,50,150.0,400.0,299.9,800.0
1,2,2,15/01/2025,100,25.0,60.0,49.9,130.0
2,3,3,18/01/2025,200,8.0,20.0,15.5,40.0
3,4,4,20/01/2025,30,80.0,210.0,159.0,420.0
4,5,5,22/01/2025,45,45.0,120.0,89.9,240.0
5,6,6,05/02/2025,60,15.0,40.0,29.9,80.0
6,7,7,05/02/2025,100,10.0,25.0,19.5,50.0
7,8,8,08/02/2025,150,5.0,12.0,12.9,32.0
8,9,9,10/02/2025,80,4.0,10.0,9.9,25.0
9,10,10,12/02/2025,40,20.0,55.0,39.9,105.0
10,11,11,01/03/2025,300,6.0,15.0,14.9,38.0
11,12,12,01/03/2025,150,12.0,30.0,25.0,65.0
12,13,13,03/03/2025,400,3.0,7.5,8.0,20.0
13,16,14,15/03/2025,50,10.0,25.0,19.9,50.0
14,17,15,15/03/2025,70,7.0,18.0,14.5,38.0
15,21,16,02/04/2025,120,8.0,20.0,15.9,40.0
16,22,17,02/04/2025,90,5.0,12.0,10.5,28.0
17,26,18,10/04/2025,1000,1.2,3.2,2.2,6.0
18,27,19,10/04/2025,200,4.5,12.0,8.9,24.0
19,28,20,12/04/2025,150,3.5,9.0,7.5,20.0
20,31,21,05/05/2025,40,20.0,55.0,39.9,105.0
21,33,22,05/05/2025,25,15.0,40.0,29.9,80.0
22,36,23,20/05/2025,100,6.0,16.0,12.5,32.0
23,41,24,01/06/2025,500,2.0,5.5,4.5,12.0
24,42,25,01/06/2025,300,3.0,8.0,6.5,18.0
25,46,26,15/06/2025,150,9.0,25.0,18.5,48.0
26,47,27,15/06/2025,200,4.0,10.5,8.9,22.0
27,51,28,10/07/2025,30,35.0,95.0,69.9,190.0
28,52,29,10/07/2025,50,12.0,32.0,24.9,65.0
29,56,30,01/08/2025,20,120.0,340.0,249.0,690.0
30,57,31,01/08/2025,40,25.0,70.0,55.0,150.0
31,61,32,15/08/2025,200,12.0,33.0,22.0,60.0
32,62,33,15/08/2025,80,5.0,13.5,10.9,28.0
33,66,34,05/09/2025,25,45.0,125.0,89.0,250.0
34,67,35,05/09/2025,30,30.0,85.0,65.0,180.0
35,71,36,20/09/2025,15,55.0,150.0,115.0,310.0
36,72,37,20/09/2025,10,70.0,200.0,149.0,410.0
37,73,38,22/09/2025,40,20.0,55.0,42.0,110.0
38,74,39,25/09/2025,20,30.0,80.0,65.0,175.0
39,75,40,28/09/2025,35,15.0,40.0,35.0,90.0

In [32]:
df_compras.to_parquet(
    '../data_sets/compras.parquet',
    engine='pyarrow',
    index=False,
    compression='snappy' )

In [50]:
df_edad_cliente = pd.read_csv('../data_lake/eda_cliente.csv')
df_edad_cliente.isna().sum()
df_edad_cliente.to_parquet(
    '../data_sets/edad_cliente.parquet',
    engine='pyarrow',
    index=False,
    compression='snappy' )

In [19]:
df_edad_cliente.head(3)

   id_tipo_cliente nombre_tipo  rango_edad_min  rango_edad_max
0                1       Niños               0              12
1                2       Joven              13              17
2                3      Adulto              18              59

In [33]:
df_forma_pago = pd.read_csv('../data_lake/forma_pago.csv')
df_forma_pago.isna().sum()

id_forma_pago    0
metodo_pago      0
dtype: int64

In [36]:
df_forma_pago.to_parquet(
    '../data_sets/forma_pago.parquet',
    engine='pyarrow',
    index=False,
    compression='snappy' )
df_forma_pago

   id_forma_pago             metodo_pago
0              1                Efectivo
1              2       Tarjeta de Débito
2              3      Tarjeta de Crédito
3              4  Transferencia Bancaria
4              5      Billetera Digital

In [35]:
df_nivel_cliente = pd.read_csv('../data_lake/nivel_cliente.csv')
df_nivel_cliente.isna().sum()

id_nivel               0
nombre_nivel           0
beneficio_descuento    0
requerimiento_anual    0
dtype: int64

In [3]:
df_nivel_cliente = df_nivel_cliente.rename(columns={'id_nivel': 'id_nivel_cliente'})
df_nivel_cliente.to_parquet(
    '../data_sets/nivel_cliente.parquet',
    engine='pyarrow',
    index=False,
    compression='snappy' )

df_nivel_cliente.head(3)

   id_nivel_cliente     nombre_nivel beneficio_descuento requerimiento_anual
0                 1  Bronce (Normal)                  0%       Sin requisito
1                 2            Plata                  5%       Compras > 500
2                 3    Oro (Premium)                 10%      Compras > 1500

In [24]:
df_cliente = pd.read_csv('../data_lake/cliente.csv')
df_cliente.isna().sum()

id_cliente          0
nombre              0
id_tipo_cliente     0
id_nivel_cliente    0
sexo                0
dtype: int64

In [51]:
df_cliente.to_parquet(
    '../data_sets/cliente.parquet',
    engine='pyarrow',
    index=False,
    compression='snappy' )
df_cliente.head(3)

   id_cliente           nombre  id_tipo_cliente  id_nivel_cliente       sexo
0           1  Sofía Valentina                3                 3   Femenino
1           2  Mateo Alejandro                3                 1  Masculino
2           3   Isabella Lucía                2                 1   Femenino

In [42]:
df_ventas = pd.read_csv('../data_lake/ventas.csv')
df_ventas.isna().sum()

id_venta         0
id_cliente       0
id_producto      0
cantidad         0
fecha_compra     0
id_tienda        0
id_empleado      0
id_forma_pago    0
dtype: int64

In [43]:
df_ventas.to_parquet(
    '../data_sets/ventas.parquet',
    engine='pyarrow',
    index=False,
    compression='snappy' )
df_ventas.head(3)

,id_venta,id_cliente,id_producto,cantidad,fecha_compra,id_tienda,id_empleado,id_forma_pago
0,1,5,12,2,01/01/2015,1,5,1
1,2,14,45,1,01/01/2015,2,14,2
2,3,22,3,3,02/01/2015,3,11,3

# Exportar al DW

In [28]:
df_cliente_ml = (df_cliente
                 .merge(df_edad_cliente, on='id_tipo_cliente')
                 .merge(df_nivel_cliente, on='id_nivel_cliente')
                 )

columnas_id = [c for c in df_cliente_ml.columns if 'id_' in c.lower() and c not in 'id_cliente']

df_final_cliente = df_cliente_ml.drop(columns= columnas_id + ['requerimiento_anual','beneficio_descuento'] )

df_final_cliente.head(3)

,id_cliente,nombre,sexo,nombre_tipo,rango_edad_min,rango_edad_max,nombre_nivel
0,1,Sofía Valentina,Femenino,Adulto,18,59,Oro (Premium)
1,2,Mateo Alejandro,Masculino,Adulto,18,59,Bronce (Normal)
2,3,Isabella Lucía,Femenino,Joven,13,17,Bronce (Normal)

In [29]:
df_ml = (
    df_ventas
    .merge(df_productos, on='id_producto')
    .merge(df_tienda, on= 'id_tienda')
    .merge(df_final_cliente, on= 'id_cliente')
    )

columnas_id = [c for c in df_ml.columns if 'id_' in c.lower()]
df_final = df_ml.drop(columns=columnas_id)

In [30]:
df_final

,cantidad,fecha_compra,nombre_producto,stock,codigo_tienda,nombre_sucursal,nombre,sexo,nombre_tipo,rango_edad_min,rango_edad_max,nombre_nivel
0,2,01/01/2015,Pantalón Denim,5.0,T1,Sucursal Norte,Camila Victoria,Femenino,Adulto,18,59,Platino (VIP)
1,1,01/01/2015,Mochila Básica,7.0,T2,Sucursal Oriente,Andrés Ricardo,Masculino,Adulto,18,59,Bronce (Normal)
2,3,02/01/2015,Cargador Rápido,13.0,T3,Sucursal Centro,Bruno Emilio,Masculino,Adulto,18,59,Plata
3,1,02/01/2015,Estante Libros,11.0,T4,Sucursal Sur,Nicolás Samuel,Masculino,Adulto,18,59,Bronce (Normal)
4,2,03/01/2015,Crema Hidratante,14.0,T1,Sucursal Norte,Santiago Jose,Masculino,Adulto,18,59,Plata
...,...,...,...,...,...,...,...,...,...,...,...,...
95,4,18/01/2015,Camiseta Algodón,8.0,T4,Sucursal Sur,Nicolás Samuel,Masculino,Adulto,18,59,Bronce (Normal)
96,1,23/01/2015,Escritorio Oficina,11.0,T1,Sucursal Norte,Isabella Lucía,Femenino,Joven,13,17,Bronce (Normal)
97,2,27/01/2015,Agenda 2026,8.0,T2,Sucursal Oriente,Marcos Pablo,Masculino,Adulto Mayor,60,74,Oro (Premium)
98,1,31/01/2015,Aceite de Oliva 500ml,9.0,T3,Sucursal Centro,Martina Natalia,Femenino,Adulto,18,59,Bronce (Normal)
99,1,15/01/2015,Caja de Herramientas,2.0,T4,Sucursal Sur,Irene Victoria,Femenino,Adulto,18,59,Oro (Premium)

In [31]:
df_final.dtypes

cantidad             int64
fecha_compra           str
nombre_producto        str
stock              float64
codigo_tienda          str
nombre_sucursal        str
nombre                 str
sexo                   str
nombre_tipo            str
rango_edad_min       int64
rango_edad_max       int64
nombre_nivel           str
dtype: object

In [32]:
df_final.to_parquet(
    'df_final.parquet',
    engine='pyarrow',
    index=False,
    compression='snappy' 
)

In [33]:
df = pd.read_parquet('df_final.parquet', engine='pyarrow')
df.head()

,cantidad,fecha_compra,nombre_producto,stock,codigo_tienda,nombre_sucursal,nombre,sexo,nombre_tipo,rango_edad_min,rango_edad_max,nombre_nivel
0,2,01/01/2015,Pantalón Denim,5.0,T1,Sucursal Norte,Camila Victoria,Femenino,Adulto,18,59,Platino (VIP)
1,1,01/01/2015,Mochila Básica,7.0,T2,Sucursal Oriente,Andrés Ricardo,Masculino,Adulto,18,59,Bronce (Normal)
2,3,02/01/2015,Cargador Rápido,13.0,T3,Sucursal Centro,Bruno Emilio,Masculino,Adulto,18,59,Plata
3,1,02/01/2015,Estante Libros,11.0,T4,Sucursal Sur,Nicolás Samuel,Masculino,Adulto,18,59,Bronce (Normal)
4,2,03/01/2015,Crema Hidratante,14.0,T1,Sucursal Norte,Santiago Jose,Masculino,Adulto,18,59,Plata